tallFlowersFromWanderingTrader true
lightningElectrifiesVines true
renewableBuddingAmethysts true
gatewaysSpawnChorus true
renewableHeartsOfTheSea true
renewableDragonHeads true
shulkerSpawnsOnDragonKill true
renewableDiamonds true
rammingWart true
foxesSpawnWithSweetBerriesChance 0.2
poisonousPotatoesConvertSpiders true
saplingsDieOnSand true
renewableEchoShards true
allayableVexes true
coralErosion true
hugeMushroomsSpreadMycelium true
renewableNetherrack true
renewableDeepslate true
renewableSwiftSneak true
traderCamels true
sniffersFromDrowneds true
suspiciousSniffers true
spreadingSmallDripleaves true
spreadingCoral true
